name: Build & Publish

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust-version: [stable]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Rust for ${{ matrix.rust-version }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-version }}
    
    - name: Build
      run: cargo build --release --verbose --package are_you_going_to_play
      
    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      with:
        tag_name: ${{ github.event.release.tag_name }}
        release_name: ${{ github.event.release.tag_name }}
    
    - name: Upload artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/release/are_you_going_to_play
        asset_name: are_you_going_to_play
        asset_content_type: application/octet-stream
