name: Build & Publish

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build binaries
      run: |
          cargo build --release --target x86_64-unknown-linux-gnu
          
    - name: Archive binaries
      uses: actions/upload-artifact@v2
      with:
          name: binaries
          path: |
            target/x86_64-unknown-linux-gnu/release/are_you_going_to_play
