name: Build & Publish

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  CARGO_TERM_COLOR: always

jobs:
  build_for_os:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust-version: [stable]
    steps:
    - uses: actions/checkout@v3

    - name: Setup Rust for ${{ matrix.rust-version }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-version }}
    
    - name: Build
      run: cargo build --release --verbose --package are_you_going_to_play-${{ matrix.os }}

  create_release:
    runs-on: ubuntu-latest
    needs: build_for_os
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    
    - name: Upload artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_path: ./target/release/are_you_going_to_play
        asset_name: are_you_going_to_play
        asset_content_type: application/octet-stream
        upload_url: ${{ steps.create_release.outputs.upload_url }}
